
# file: #roles/common/tasks/amazon.yml

# System configs

- name: common / creates /DATA/etc
  file:
    path="{{ project_etc_root }}"
    mode=0644
    owner=root
    group=root
    state=directory
  when: max_action == "sync" and max_what == "system"
  tags: sync

- name: common / reates /DATA/src
  file:
    path="{{ project_etc_root }}"
    mode=0644
    owner=root
    group=root
    state=directory
  when: max_action == "sync" and max_what == "system"
  tags: sync

 
# packages

- name: install amazon base packages 1
  yum: pkg={{ item }} state=latest
  with_items: amazon_pkgs
  when: max_action == "setup" and max_what == "system"
  tags: setup

- name: install amazon group packages 2
  yum: pkg="{{ item }}" state=latest
  with_items: amazon_group_pkgs
  when: max_action == "setup" and max_what == "system"
  tags: setup

- name: install amazon group packages 3
  yum: pkg={{ item }} state=latest
  with_items: common_pkgs
  tags: setup

- name: yum clean all
  command: yum clean all
  ignore_errors: true
  when: max_action == "setup" and max_what == "system"
  tags: setup


# setup daemons

- service: name=docker state=started enabled=True
